apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 243135625567-o0m3kaph8j5umqno6a2s2c35cqpv8nu0.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: http://57.182.61.183.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
