apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLVg0MTVna18zSXlKM3N6eUNQNnVtUk1EbEpTNEc= # Base64 for google key
  NEXTAUTH_SECRET: d2dwelpSdWtNVDI1ejlNN25lZFMzQTF1akhiRGRWandETTlQbFdqVnJTRT0= # Base64 for auth key
  NEXT_PUBLIC_API_KEY: QUl6YVN5QTZ5U3YtTFhlRWx3VUVOX2EwaTFxSWRoOVA2Uk1JYm1z # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==  # Base64 for admin@123
